### ISSUE TITLE
Remove persistent/iiifconfig/cantaloupe.properties from version control

### ISSUE THREAD

**Issue by patdunlavey** [esmero/archipelago-deployment#124]
The contents of `/persistent/iiifconfig/cantaloupe.properties` may be different depending on the particular deployment, even within a particular project. In our case we need different cantaloupe.properties for local development vs. staging and production environments. 

Tracking this file in the git repo makes it hard to customize it as needed in the various deployments.

Proposed solution: 

1. Rename this file `default.cantaloupe.properties`
2. .gitignore `/persistent/iiifconfig/cantaloupe.properties`
3. In `setup.sh` or another script, add a command to copy `/persistent/iiifconfig/default.cantaloupe.properties` to `/persistent/iiifconfig/cantaloupe.properties` and set file permissions as appropriate.
4. Document how to customize the minio setup, how to set up to use S3, etc., including how to modify this `cantaloupe.properties` file.

**Comment by patdunlavey** [comment]
Tagging @dmer and @DiegoPino

**Comment by patdunlavey** [comment]
Pull request created: https://github.com/esmero/archipelago-deployment/pull/125

Let me know if this does or does not make sense @DiegoPino ?

**Comment by DiegoPino** [comment]
Hi @patdunlavey thanks for you issue and pull. This pull makes sense but I feel its better suited for https://github.com/esmero/archipelago-deployment-live/tree/1.0.0-RC3

The rational behind this is:
- Archipelago Deployment will be easier to support (help/code/etc) for all of us if its not meant to highly customized and if the instructions do not add more manual steps to the instructions
- Archipelago Deployment Live expose all iiif configs via docker-compose environmental, which means the file can be totally be left untouched and configs can be set either manually on the composer or via .env file
- If you are using/staying with this repo for dev/live deployments adding it to .gitignore is fine (so will merge that part of the pull) but there is no need of renaming it. 

To accomplish your need I will suggest a different approach (which I agree we can document as an "advanced" option). copy the cantaloupe.properties to myown.cantaloupe.properties and change this line. I may missing a use case so please correct me here.

https://github.com/esmero/archipelago-deployment/blob/1.0.0-RC3/docker-compose-linux.yml#L89
from 

  - ${PWD}/persistent/iiifconfig:/etc/cantaloupe
to 
  - ${PWD}/persistent/iiifconfig/myown.cantaloupe.properties:/etc/cantaloupe/cantaloupe.properties
Since docker-compose is already excluded from version tracking that would allow you even to have multiple `properties` files and track them in your own branches

Please let me know if my idea servers your need. If https://github.com/esmero/archipelago-deployment-live/tree/1.0.0-RC3 does not suit your production needs very happy to make it better.  Thanks a lot

**Comment by aksm** [comment]
I think @DiegoPino 's rationale makes sense so closing this for now. Please feel free to re-open if there are any other thoughts/suggestions/ideas/questions.
