### ISSUE TITLE
Color css does not load with new Archipelago deployment

### ISSUE THREAD

**Issue by mitchellkeaney** [esmero/archipelago-deployment#59]
When deploying an Archipelago from scratch, the new Archipelago base theme does not render right away.
This appears to be a known issue with the color module: https://www.drupal.org/project/drupal/issues/2995825

Quick fix for Archipelago users is to go to `/admin/appearance/settings/archipelago_subtheme`, click `Save` at the very bottom, clear your cache and refresh. Theme should then load and be good to go!

**Comment by DiegoPino** [comment]
@mitchellkeaney good catch! Just saw same behavior on a SENYLRC deployment but i thought it was because the installation was done in a hurry 🤦  Since the files inside 
web/sites/default/files are all ignored, the automatic caches (which wrongly only are generated manually when saving that form) are never committed.  Drupal never finishes to amaze us.

This recent pull should fix this
https://github.com/esmero/archipelago-deployment/commit/85b8a54ce39474e44cc25d83716d819c02d43133 
(git pull if you already have AP installed and fear you can not navigate a blank page)

Doing a fresh install, but pretty sure this should have us moving in no time

**Comment by DiegoPino** [comment]
Yep. that did the trick and fixed on our site! Good to have this around as a reminder when we go 1.0.0 and use pumpkin and purple as main colors!

**Comment by DiegoPino** [comment]
Fixed via https://github.com/esmero/archipelago-deployment/commit/85b8a54ce39474e44cc25d83716d819c02d43133

**Comment by mitchellkeaney** [comment]
Oooh, but I like the pink! Though, pumpkin sounds nice (to eat) too.
